aws-samples/aws-last-mile-delivery-hyperlocal

- LICENSE_THIRDPARTY.txt
- package.json
- packages/@prototype/external-provider-mock/src/ExternalWebhookProviderStack/WebhookInvoker/@lambda/package.json
- packages/@prototype/internal-provider/src/DispatchEngineOrchestrator/OrchestratorHelperLambda/@lambda/package.json
- packages/@prototype/internal-provider/src/DriverEventHandler/DriverStatusChangeHandler/@lambda/package.json
- packages/@prototype/order-manager/src/OrderManager/ProviderRuleEngine/@lambda/package.json
- packages/@prototype/provider-impl/src/ExamplePollingProvider/lambdas/CancelOrder/@lambda/package.json
- packages/@prototype/provider-impl/src/ExamplePollingProvider/lambdas/ExamplePolling/@lambda/package.json
- packages/@prototype/provider-impl/src/ExamplePollingProvider/lambdas/GetOrderStatus/@lambda/package.json
- packages/@prototype/provider-impl/src/ExamplePollingProvider/lambdas/RequestOrderFulfillment/@lambda/package.json
- packages/@prototype/provider-impl/src/ExampleWebhookProvider/lambdas/CancelOrder/@lambda/package.json
- packages/@prototype/provider-impl/src/ExampleWebhookProvider/lambdas/GetOrderStatus/@lambda/package.json
- packages/@prototype/provider-impl/src/ExampleWebhookProvider/lambdas/RequestOrderFulfillment/@lambda/package.json
- packages/@prototype/simulator/src/SimulatorManagerStack/CustomerSimulatorLambda/CustomerGeneratorStepFunction/@lambda/package.json
- packages/@prototype/simulator/src/SimulatorManagerStack/CustomerSimulatorLambda/CustomerGeneratorStepFunction/@lambda/src/commands/generateCustomer.js
- packages/@prototype/simulator/src/SimulatorManagerStack/RestaurantSimulatorLambda/RestaurantGeneratorStepFunction/@lambda/package.json
- packages/@prototype/simulator/src/SimulatorManagerStack/RestaurantSimulatorLambda/RestaurantGeneratorStepFunction/@lambda/src/commands/generateRestaurant.js
- prototype/simulator/container/package.json
- prototype/simulator/container/src/common/lib/userData.js
- prototype/simulator/website/LICENSE_THIRDPARTY.txt
- prototype/simulator/website/package.json
- reports/yarn-audit.html
- yarn.lock
NA
- upgrade the following dependencies: `axios`, `lerna`, `aws-amplify`
- remove `shortid` (deprecated) in favour of `nanoid`
- fix simulator website build issue
> fix(dependencies): fix simulator-website build issue and upgrade dependencies

- packages/@aws-play/cdk-lambda/src/declared/DeclaredLambdaFunction.ts
- packages/@prototype/api-geotracking/src/ApiGeofencing/GeofencingService/index.ts
- packages/@prototype/external-provider-mock/src/ExternalProviderSetup/index.ts
- packages/@prototype/external-provider-mock/src/ExternalWebhookProviderStack/WebhookInvoker/index.ts
- packages/@prototype/internal-provider/src/DriverEventHandler/SubMinuteExecutionStepFunction/index.ts
- packages/@prototype/lambda-common/src/ESClientLayer/index.ts
- packages/@prototype/lambda-common/src/LambdaUtils/index.ts
- packages/@prototype/lambda-common/src/RedisClientLayer/index.ts
- packages/@prototype/live-data-cache/src/LiveDataCache/ElasticSearchCluster/ESInitialSetup/index.ts
- packages/@prototype/order-manager/src/OrderManager/OrderManagerHandler/index.ts
- packages/@prototype/order-manager/src/OrderManager/OrderManagerHelper/index.ts
- packages/@prototype/order-manager/src/OrderManager/ProviderRuleEngine/index.ts
- packages/@prototype/provider/src/ProviderInitialSetup/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/CustomerSimulatorLambda/CustomerEraserStepFunction/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/CustomerSimulatorLambda/CustomerGeneratorStepFunction/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/CustomerSimulatorLambda/CustomerStarterStepFunction/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/CustomerSimulatorLambda/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/EventSimulatorLambda/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/GraphhopperManager/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/OrderSimulatorLambda/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/RestaurantSimulatorLambda/RestaurantEraserStepFunction/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/RestaurantSimulatorLambda/RestaurantGeneratorStepFunction/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/RestaurantSimulatorLambda/RestaurantStarterStepFunction/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/RestaurantSimulatorLambda/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/SimulatorManagerLambda/ECSStepFunctionInvoker/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/SimulatorManagerLambda/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/StatisticsLambda/index.ts
- reports/cfn-nag-report.json
*Issue #, if available:* #23
* set architecture to `lambda.Architecture.ARM_64` as default in `DeclaredLambdaFunction`
* removed `runtime` and `architecture` parameters for all `DeclaredLambdaFunction` instantiation
* added `architecture: lambda.Architecture.ARM_64` for all `new lambda.Function`
> feat: lambdas use graviton architecture

- packages/@prototype/internal-provider/src/DispatchEngineOrchestrator/OrchestratorHelperLambda/@lambda/src/commands/invokeDispatch.js
- packages/@prototype/internal-provider/src/DispatchEngineOrchestrator/OrchestratorHelperLambda/@lambda/src/commands/queryDispatch.js
- prototype/dispatch/order-dispatcher/docs/README.md
- prototype/dispatch/order-dispatcher/docs/dispatch-engine-assign-drivers-sequence.plantuml
- prototype/dispatch/order-dispatcher/package.json
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/api/instant/mixedpickupdropoff/DispatcherResource.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/api/instant/mixedpickupdropoff/RoutingResource.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/api/instant/sequential/DispatcherResource.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/api/instant/sequential/DispatcherService.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/api/instant/sequential/RoutingResource.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/api/instant/sequential/TestResource.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/domain/planningentity/instant/mixedpickupdropoff/CustomerVisit.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/domain/planningentity/instant/mixedpickupdropoff/PlanningDriver.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/domain/planningentity/instant/mixedpickupdropoff/PlanningVisit.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/domain/planningentity/instant/mixedpickupdropoff/RestaurantVisit.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/domain/planningentity/instant/mixedpickupdropoff/VisitOrDriver.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/domain/planningentity/instant/sequential/DeliveryOrDriver.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/domain/planningentity/instant/sequential/PlanningDelivery.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/domain/planningentity/instant/sequential/PlanningDriver.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/planner/solution/instant/mixedpickupdropoff/DispatchingConstraintProvider.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/planner/solution/instant/mixedpickupdropoff/DispatchingSolution.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/planner/solution/instant/mixedpickupdropoff/SolutionConsumer.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/planner/solution/instant/sequential/DispatchingConstraintProvider.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/planner/solution/instant/sequential/DispatchingSolution.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/planner/solution/instant/sequential/SolutionConsumer.java
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/util/Constants.java
- prototype/dispatch/order-dispatcher/src/main/resources/application-docker.properties
- prototype/dispatch/order-dispatcher/src/main/resources/application.properties
- prototype/dispatch/order-dispatcher/src/main/resources/instant/mixedpickupdropoff/dispatchSolverConfig.xml
- prototype/dispatch/order-dispatcher/src/main/resources/instant/sequential/dispatchSolverConfig.xml
*Issue #, if available:* #2
* changed `v1` to `instant/mixedpickupdropoff`
* changed `v2` to `instant/sequential`
* updated URLs in lambdas that call dispatcher
> refactor(dispatcher): named versions for configs and classes

- prototype/simulator/website/package.json
- prototype/simulator/website/src/components/DestinationAdditionalInputs/index.tsx
- prototype/simulator/website/src/components/EntityDetailsComponent/index.tsx
- prototype/simulator/website/src/components/EntitySimulationSummary/index.tsx
- prototype/simulator/website/src/components/EventDetails/index.tsx
- prototype/simulator/website/src/components/GenerateEntityComponent/index.tsx
- prototype/simulator/website/src/components/MapComponent/AssignmentMap.tsx
- prototype/simulator/website/src/components/OriginAdditionalInputs/index.tsx
- prototype/simulator/website/src/pages/Dispatching/index.tsx
- prototype/simulator/website/src/pages/Dispatching/table-columns.tsx
- prototype/simulator/website/src/pages/Login/index.tsx
- prototype/simulator/website/src/pages/NewPassword/index.tsx
- prototype/simulator/website/src/pages/NewPolygon/index.tsx
- prototype/simulator/website/src/pages/NewSimulation/index.tsx
- prototype/simulator/website/src/pages/Orders/index.tsx
- prototype/simulator/website/src/pages/Orders/table-columns.tsx
- prototype/simulator/website/src/pages/Polygons/index.tsx
- prototype/simulator/website/src/pages/SimulationDetails/index.tsx
- prototype/simulator/website/src/pages/Simulations/index.tsx
- yarn.lock
* `Button` icons must have been replaced with `@material-ui/icon` types
* build failed due to some typescript type checks
* `aws-northstar` package version bumped to `^1.3.12`
* added `@material-ui/icons` package
> fix(website): website builds with updated northstar

- packages/@prototype/provider-impl/src/InstantDeliveryProvider/index.ts
- prototype/infra/bin/dev-infra.ts
- prototype/infra/config/default.yaml
- prototype/infra/package.json
*Issue #, if available:* #46
* created `default.yaml` in `infra/config` -- this is the base config with **ALL** parameters (with description)
* renamed `instantDeliveryProviderSettings.shardCount` to `instantDeliveryProviderSettings.orderBatchStreamShardCount`
* `local-XXX.yaml` configs (gitignored) should only include those parameters that are needed (ie `env`, `namespace`, `administratorEmail`)
> feat(infra): switch infra config to yaml with comments

- LICENSE_THIRDPARTY.txt
- package.json
- prototype/simulator/container/package.json
- prototype/simulator/website/LICENSE_THIRDPARTY.txt
- reports/yarn-audit.html
- yarn.lock
- update the `package.json` file to include `no-hoist` dependencies on the simulator container so that during the build the dependencies will be included in the docker image
> chore(sim): add no-hoist to simulator dependencies

- LICENSE_THIRDPARTY.txt
- prototype/simulator/container/package.json
- prototype/simulator/website/LICENSE_THIRDPARTY.txt
- reports/yarn-audit.html
- simplify no-hoist configuration
> chore(sim): simplify no-hoist configuration for simulator container

- packages/@aws-play/cdk-web/src/hosting/WebsiteHosting/CloudFrontWaf/index.ts
- packages/@aws-play/cdk-web/src/hosting/WebsiteHosting/index.ts
- packages/@prototype/common/src/constructs/DefaultWaf/index.ts
- packages/@prototype/common/src/constructs/index.ts
- packages/@prototype/dispatch-setup/src/DispatchSetup/DispatchEcsService/index.ts
- packages/@prototype/dispatch-setup/src/GraphhopperSetup/index.ts
- packages/@prototype/external-provider-mock/src/ExternalPollingProviderStack/index.ts
- packages/@prototype/external-provider-mock/src/ExternalWebhookProviderStack/index.ts
- packages/@prototype/provider/src/ProviderBase/index.ts
- prototype/infra/lib/stack/nested/MicroServiceStack/index.ts
- prototype/infra/lib/stack/root/SimulatorMainStack/index.ts
*Issue #, if available:* closes #55
- add WAF in front of ALB, CloudFront and API Gateway resources
> fix(infra): add waf to alb, cloudfront and api gateway resources

- package.json
- just add `build:order-dispatcher` to the `build:all` command
> chore(package): fix build:all command to include dispatcher build

- package.json
- packages/@aws-play/cdk-web/src/hosting/WebsiteHosting/CloudFrontWaf/index.ts
- packages/@aws-play/cdk-web/src/hosting/WebsiteHosting/index.ts
- packages/@prototype/appconfig/src/AppConfigNestedStack/ConfigStorage/index.ts
- packages/@prototype/common/src/constructs/DefaultWaf/index.ts
- packages/@prototype/common/src/constructs/HyperlocalBucket/index.ts
- packages/@prototype/common/src/constructs/HyperlocalTable/index.ts
- packages/@prototype/common/src/constructs/index.ts
- packages/@prototype/data-storage/src/DataStoragePersistent/index.ts
- packages/@prototype/dispatch-setup/src/DispatchSetup/DispatchEcsService/index.ts
- packages/@prototype/dispatch-setup/src/GraphhopperSetup/index.ts
- packages/@prototype/external-provider-mock/src/ExternalPollingProviderStack/index.ts
- packages/@prototype/external-provider-mock/src/ExternalWebhookProviderStack/DataStack/index.ts
- packages/@prototype/external-provider-mock/src/ExternalWebhookProviderStack/index.ts
- packages/@prototype/monitoring/src/Monitoring/index.ts
- packages/@prototype/provider/src/ProviderBase/index.ts
- packages/@prototype/simulator/src/SimulatorDataStack/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/index.ts
- prototype/infra/lib/stack/nested/MicroServiceStack/index.ts
- prototype/infra/lib/stack/root/SimulatorMainStack/index.ts
- add common S3 Bucket and DDB Table constructs to avoid repeating the base properties in every new resource 
> common bucket table constructs

- packages/@prototype/dispatch-setup/src/GraphhopperSetup/docker/Dockerfile
- prototype/dispatch/order-dispatcher/src/main/docker/instant/sequential/Dockerfile
- prototype/scripts/graphhopper/Dockerfile
- attempt to fix docker build on x86/64 processors 
> fix(build): add platform on docker prod stage build

- prototype/simulator/container/package.json
- remove `workspaces` configuration from the `package.json` in the simulator container as it creates issues when tries to build the docker image
> fix(sim): remove workspaces configuration from package.json

- packages/@prototype/instant-delivery-provider/src/DispatchEngineOrchestrator/OrchestratorHelperLambda/@lambda/src/config/index.js
- packages/@prototype/instant-delivery-provider/src/DispatchEngineOrchestrator/OrchestratorHelperLambda/@lambda/src/lib/callbackTrigger.js
- packages/@prototype/instant-delivery-provider/src/DriverEventHandler/DriverStatusChangeHandler/@lambda/callbackTrigger.js
- packages/@prototype/instant-delivery-provider/src/DriverEventHandler/DriverStatusChangeHandler/@lambda/config/index.js
- packages/@prototype/instant-delivery-provider/src/DriverEventHandler/DriverStatusChangeHandler/index.ts
- packages/@prototype/instant-delivery-provider/src/DriverEventHandler/index.ts
- prototype/infra/lib/stack/nested/ProviderStack/index.ts
- fix typo on instant delivery provider property 
> chore(infra): fix instant delivery property typo

- packages/@prototype/lambda-common/src/LambdaInsights/index.ts
- fix Lambda insights layer to use Arm build (issue introduced by #23)
> fix(infra): fix lambda insights layer to use ARM version

- packages/@prototype/simulator/src/SimulatorDataStack/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/DestinationStarterStepFunction/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/index.ts
- prototype/infra/lib/stack/root/SimulatorMainStack/index.ts
- move simulator config bucket to the simulator persisted stack
> fix(infra): move configuration bucket in simulator persisted stack

- packages/@prototype/instant-delivery-provider/src/DispatchEngineOrchestrator/OrchestratorHelperLambda/@lambda/src/commands/sendToDriver.js
*Issue #, if available:* #51
- add comment as reminder
> docs(instant-delivery): add TODO to remember to change the code according to #51

- prototype/simulator/website/src/api/GeotrackingAPI.ts
- prototype/simulator/website/src/pages/DriverQuery/index.tsx
- thanks to the changes done on #82, this PR adds the ability on the simulator UI to query drivers using rectangular shapes (providing width / height) 
> feat(simulator-web): update UI to give the option to query drivers by box

- packages/@prototype/lambda-functions/src/LambdaFunctions/OpenSearchInitialSetupLambda/@lambda/index.js
- packages/@prototype/lambda-functions/src/LambdaFunctions/OpenSearchInitialSetupLambda/index.ts
- update custom resource Lambda to use the right architecture
- fix code to create the open-search index correctly
> fix(open-search): fix customer resource that create open search index

- packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/DestinationStarterStepFunction/@lambda/src/lib/ecs.js
- prototype/simulator/container/src/destinationApp.js
- fix destination app to add option instead of action
- add handling of optional parameter when creating ECS task
> fix(simulator): fix destination app 

- packages/@prototype/simulator/src/ECSContainerStack/index.ts
- remove un-required ECR repository as the images are pushed directly to the repository created by CDK 
> chore(infra): remove un-required elastic container repository

- LICENSE_THIRDPARTY.txt
- packages/@prototype/simulator/src/SimulatorDataStack/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/APIGatewayResourceStack/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/@lambda/src/config/index.js
- packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/DestinationStarterStepFunction/@lambda/src/commands/iterate.js
- packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/DestinationStarterStepFunction/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/S3PresignedUrlLambda/@lambda/index.js
- packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/S3PresignedUrlLambda/@lambda/package.json
- packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/S3PresignedUrlLambda/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/index.ts
- prototype/simulator/website/LICENSE_THIRDPARTY.txt
- prototype/simulator/website/package.json
- prototype/simulator/website/src/api/Destination.ts
- prototype/simulator/website/src/components/DestinationAdditionalInputs/index.tsx
- reports/yarn-audit.html
- yarn.lock
- add ability to replay existing events by providing an order event file uploaded by the end user
> feat(simulator): add file upload capability to replay past events

- packages/@prototype/simulator/src/ECSContainerStack/SimulatorContainer/index.ts
- packages/@prototype/simulator/src/ECSContainerStack/index.ts
- prototype/infra/lib/stack/root/SimulatorPersistentStack/index.ts
- prototype/simulator/container/src/common/lib/s3.js
- prototype/simulator/container/src/destination/destination.js
- prototype/simulator/container/src/driver/index.js
- prototype/simulator/website/src/api/Destination.ts
- fix policy used by the task definition to allow `s3:GetObject`
- fix destination simulation minor issues
- minor UI fixes
> fix(simulator): fix destination simulator policy

- packages/@prototype/simulator/src/SimulatorManagerStack/OrderSimulatorLambda/@lambda/src/commands/createOrder.js
- packages/@prototype/simulator/src/SimulatorManagerStack/OriginSimulatorLambda/OriginGeneratorStepFunction/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/OriginSimulatorLambda/index.ts
- packages/@prototype/simulator/src/SimulatorManagerStack/index.ts
- prototype/infra/lib/stack/root/SimulatorMainStack/index.ts
- prototype/simulator/container/src/destination/destination.js
- prototype/simulator/website/src/pages/Destinations/index.tsx
- prototype/simulator/website/src/pages/NewSimulation/index.tsx
- fix order submission for events replay scenario
- minor ui fixes
> fix(simulator): fix order submission when events file is utilised to replay existing scenario

- packages/@prototype/simulator/src/SimulatorManagerStack/OriginSimulatorLambda/OriginGeneratorStepFunction/index.ts
- minor fix to env variable generation 
> fix(infra): fix origin generator env variable

- packages/@prototype/order-manager/src/OrderManager/OrderManagerStepFunction/index.ts
- packages/@prototype/order-manager/src/OrderManager/ProviderRuleEngine/@lambda/src/commands/findProvider.js
- update order manager stepfunctions workflow to avoid using the same provider twice. This change will prevent the workflow from selecting a provider that has already failed and would also reject the order in case no provider are longer available as result from multiple retries 
> fix(order-manager): add logic to avoid using the same provider again 

- prototype/infra/config/default.yaml
- prototype/infra/lib/stack/nested/ProviderStack/index.ts
- prototype/infra/lib/stack/root/BackendStack/index.ts
- fix nullable parameter 
- add container name in the dispatch settings
> fix(infra): fix nullable parameter and add dispatcher container name in the settings

- packages/@prototype/api-geotracking/package.json
- packages/@prototype/data-storage/src/DataStoragePersistent/index.ts
- packages/@prototype/dispatch-setup/src/DispatchSetup/DispatchEcsService/index.ts
- packages/@prototype/dispatch-setup/src/DispatchSetup/DispatchHosting/index.ts
- packages/@prototype/dispatch-setup/src/DispatchSetup/index.ts
- packages/@prototype/lambda-functions/package.json
- prototype/dispatch/delivery-dispatch/apps/app-core/src/main/java/dev/aws/proto/apps/appcore/config/DriverClientProperties.java
- prototype/dispatch/delivery-dispatch/apps/app-core/src/main/java/dev/aws/proto/apps/appcore/data/DriverQueryClient.java
- prototype/dispatch/delivery-dispatch/apps/app-core/src/main/java/dev/aws/proto/apps/appcore/data/DriverQueryManager.java
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/pom.xml
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/java/dev/aws/proto/apps/instant/sequential/config/DdbProperties.java
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/java/dev/aws/proto/apps/instant/sequential/data/DdbAssignmentService.java
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/resources/application.properties
- prototype/dispatch/delivery-dispatch/core/core-impl/pom.xml
- prototype/dispatch/delivery-dispatch/core/core-impl/src/main/java/dev/aws/proto/core/util/aws/SsmUtility.java
- prototype/dispatch/delivery-dispatch/core/routing/src/main/java/dev/aws/proto/core/routing/config/RoutingConfig.java
- prototype/dispatch/delivery-dispatch/core/routing/src/main/java/dev/aws/proto/core/routing/config/RoutingProperties.java
- prototype/dispatch/delivery-dispatch/pom.xml
- prototype/dispatch/order-dispatcher/src/main/docker/instant/sequential/Dockerfile
- prototype/dispatch/order-dispatcher/src/main/docker/instant/sequential/config/application-docker.properties
- prototype/dispatch/order-dispatcher/src/main/docker/instant/sequential/graphhopper/config.yml
- prototype/dispatch/order-dispatcher/src/main/java/com/aws/proto/dispatching/api/health/ReadinessCheckResource.java
- prototype/infra/config/default.yaml
- prototype/infra/lib/stack/nested/DispatcherStack/index.ts
- prototype/infra/lib/stack/nested/MicroServiceStack/index.ts
- prototype/infra/lib/stack/root/BackendStack/index.ts
- prototype/infra/lib/stack/root/PersistentBackendStack/index.ts
*Issue #, if available:* #97
* [infra] create SSM parameter store entries for GeoTrackingApi URL, 2 ddb tables
* [dispatch] update config entries to store parameter store keys
* [dispatch] fetch SSM parameter values and use in various parts in the dispatcher
* [dispatch] remove s3 mapfile download
* [dispatch][old]: docker build fixes
> feat(delivery-dispatch/config): configs from SSM parameter store

- prototype/dispatch/delivery-dispatch/apps/app-core/src/main/java/dev/aws/proto/apps/appcore/api/health/ReadinessCheckResource.java
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/docker/Dockerfile
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/resources/application.properties
Instant sequential domain app dockerization added
> feat(delivery-dispatch/instant/sequential): dockerization added

- prototype/dispatch/delivery-dispatch/apps/app-core/src/main/java/dev/aws/proto/apps/appcore/api/DispatchService.java
- prototype/dispatch/delivery-dispatch/apps/app-core/src/main/java/dev/aws/proto/apps/appcore/api/response/DispatchResult.java
- prototype/dispatch/delivery-dispatch/apps/app-core/src/main/java/dev/aws/proto/apps/appcore/data/DdbServiceBase.java
- prototype/dispatch/delivery-dispatch/apps/app-core/src/main/java/dev/aws/proto/apps/appcore/data/DriverQueryManager.java
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/docker/Dockerfile
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/java/dev/aws/proto/apps/instant/sequential/api/DispatchService.java
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/java/dev/aws/proto/apps/instant/sequential/api/response/DispatchResult.java
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/java/dev/aws/proto/apps/instant/sequential/data/DdbAssignmentService.java
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/java/dev/aws/proto/apps/instant/sequential/data/DriverQueryClient.java
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/java/dev/aws/proto/apps/instant/sequential/data/DriverQueryManager.java
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/java/dev/aws/proto/apps/instant/sequential/domain/planning/PlanningDelivery.java
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/java/dev/aws/proto/apps/instant/sequential/domain/planning/PlanningDriver.java
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/java/dev/aws/proto/apps/instant/sequential/location/DestinationLocation.java
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/java/dev/aws/proto/apps/instant/sequential/location/OriginLocation.java
- prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/java/dev/aws/proto/apps/instant/sequential/planner/solution/SolutionConsumer.java
- prototype/dispatch/delivery-dispatch/core/core-impl/src/main/java/dev/aws/proto/core/Order.java
- prototype/dispatch/delivery-dispatch/core/routing/src/main/java/dev/aws/proto/core/routing/distance/DistanceMatrix.java
- prototype/dispatch/delivery-dispatch/core/routing/src/main/java/dev/aws/proto/core/routing/location/Coordinate.java
- prototype/dispatch/delivery-dispatch/core/routing/src/main/java/dev/aws/proto/core/routing/location/CoordinateWithId.java
- prototype/dispatch/delivery-dispatch/core/routing/src/main/java/dev/aws/proto/core/routing/location/LocationBase.java
- prototype/dispatch/delivery-dispatch/core/routing/src/main/java/dev/aws/proto/core/routing/route/DeliverySegment.java
- prototype/dispatch/delivery-dispatch/core/routing/src/main/java/dev/aws/proto/core/routing/route/GraphhopperRouter.java
- prototype/dispatch/delivery-dispatch/core/routing/src/main/java/dev/aws/proto/core/routing/route/SegmentRoute.java
- prototype/dispatch/delivery-dispatch/pom.xml
- prototype/dispatch/order-dispatcher/src/main/docker/instant/sequential/Dockerfile
- prototype/dispatch/order-dispatcher/src/main/docker/instant/sequential/config/application-docker.properties
*Issue #, if available:* #51
* fixed a few issues with creating the docker image for instant-sequential dispatcher
* fixed data/bean class annotations and required overrides
* driver query client uses dynamic URL retreived from parameter store
* `DispatchResult` restructured to desired format
> feat(delivery-dispatch): instant sequential delivery provider performs dispatch and returns new object structure for job

- packages/@prototype/instant-delivery-provider/src/DispatchEngineOrchestrator/DispatchEngineOrchestrator/index.ts
- packages/@prototype/instant-delivery-provider/src/DispatchEngineOrchestrator/OrchestratorHelperLambda/@lambda/src/commands/queryDispatch.js
- packages/@prototype/instant-delivery-provider/src/DispatchEngineOrchestrator/OrchestratorHelperLambda/@lambda/src/commands/sendToDriver.js
- packages/@prototype/simulator/src/SimulatorManagerStack/DispatcherAssignmentQueryLambda/@lambda/index.js
- prototype/simulator/website/src/components/MapComponent/AssignmentMap.tsx
- prototype/simulator/website/src/components/NavigationBar/index.tsx
- prototype/simulator/website/src/layout/index.tsx
- prototype/simulator/website/src/pages/InstantDeliveryDispatching/index.tsx
- prototype/simulator/website/src/pages/InstantDeliveryDispatching/table-columns.tsx
*Issue #, if available:* #51
- change backend to include route level routing to allow the web simulator to display it successfully
- update web-ui to reflect changes on the dispatch assignments view
> fix(simulator): fix web-ui to show dispatcher job (instant delivery) with routing details

- packages/@prototype/instant-delivery-provider/src/DriverEventHandler/DriverStatusChangeHandler/@lambda/index.js
- prototype/simulator/container/src/destination/destination.js
- prototype/simulator/container/src/driver/commands/newOrder.js
*Issue #, if available:* #51
- fix the replay event code after change to the payload structure
> fix(simulator): fix replay event code to consider payload changes

- packages/@prototype/lambda-common/src/TablePolicy/index.ts
* add `BATCH_WRITE_ITEM` to table policy statement for DDB
> fix(lambda-common): enable updateDDBTablePolicy to BATCH_WRITE_ITEM

- packages/@prototype/data-storage/src/DataStoragePersistent/index.ts
* Remove `createdAt` sortKey from sdd solverjob ddb table
> fix(data-storage): remove sortKey from sdd-solverjobs table

- LICENSE_THIRDPARTY.txt
- packages/@prototype/data-storage/src/DataStoragePersistent/index.ts
- packages/@prototype/dispatch-setup/src/DispatchSetup/SameDayDispatchEcsService/index.ts
- packages/@prototype/dispatch-setup/src/DispatchSetup/index.ts
- prototype/infra/config/default.yaml
- prototype/infra/lib/stack/nested/DispatcherStack/index.ts
- prototype/infra/lib/stack/root/BackendStack/index.ts
- prototype/simulator/website/LICENSE_THIRDPARTY.txt
- reports/cfn-nag-report.json
- reports/yarn-audit.html
* added `sameday-directpudo-hubs` ddb table along with the ssm parameter to use in the dispatcher
> feat(infra): add sdd hubs ddb table and wire it up

- packages/@prototype/dispatch-setup/src/GraphhopperSetup/docker/Dockerfile
- packages/@prototype/dispatch-setup/src/GraphhopperSetup/docker/graphhopper-config.yml
- reports/docker/graphhopper-40-report.txt
* updated Graphhopper dockerization for easier maintenance
* added `trivy` report
> fix(dispatch-setup): graphhhopper dockerization rewritten

- prototype/simulator/container/Dockerfile
- reports/docker/ecs-container-simulator-report.txt
- fix few small issues on the ECS Docker image for the simulator (root user, `npm audit fix`)
- attach trivy scan report file
> chore(simulator): add trivy scan report for ecs simulator app

- prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/api/DispatchService.java
- prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/domain/planning/PlanningVehicle.java
- prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/domain/planning/PlanningVisit.java
- prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/domain/planning/capacity/CurrentCapacity.java
- prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/domain/planning/capacity/MaxCapacity.java
- prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/planner/solution/DispatchConstraintProvider.java
- prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/resources/solver-config.xml
- prototype/dispatch/delivery-dispatch/package.json
- prototype/dispatch/delivery-dispatch/pom.xml
* remove duplicate orders having same orderIDs
* add vehicle capacity constraint
> feat(delivery-dispatch): add vehicle capacity constraint

- prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/api/DispatchService.java
- prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/data/DdbVehicleCapacityService.java
- prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/domain/planning/PlanningVehicle.java
- prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/domain/planning/PlanningVisit.java
- prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/domain/planning/capacity/CurrentCapacity.java
- prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/domain/planning/capacity/MaxCapacity.java
- prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/domain/planning/capacity/VehicleType.java
- prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/planner/solution/DispatchConstraintProvider.java
* fix reading vehicle capacity settings from ddb
* finetune constraints for the same-day domain
> feat(delivery-dispatch/apps/sameday): finetune constraints

- LICENSE_THIRDPARTY.txt
- prototype/simulator/website/LICENSE_THIRDPARTY.txt
- reports/yarn-audit.html
- yarn.lock
*Issue #, if available:* #81, #80, #72
* bump `follow-redirects` as recommended in #80
* bump `vm2` as recommended in #81
* bump `url-parse` as recommended in #72
* doing the necessary changes without removing dependencies needed
> chore(deps): update dependabot recommended deps

- packages/@prototype/provider-impl/package.json
- packages/@prototype/simulator/package.json
*Issue #, if available:* closes #144
- added missing dependencies on the packages to prevent build errors
- tested by running `yarn clean` and `yarn build` -> packages are built correctly without build errors
Note: **depcheck** suggested in the issue #144 generate some false positive
> fix(dependencies): add missing dependencies in packages to fix build issues

- packages/@prototype/dispatch-setup/src/DispatchSetup/DispatchEcsCluster/index.ts
* add imds toggle to v2 in dispatch ecs cluster's asg
> fix(dispatch-setup): add imds toggle to v2 in dispatch ecs cluster's asg
