aws-samples/aws-last-mile-delivery-hyperlocal

packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/DestinationStarterStepFunction/index.ts, packages/@prototype/simulator/src/SimulatorManagerStack/GraphhopperManager/@lambda/src/index.js, packages/@prototype/simulator/src/SimulatorManagerStack/GraphhopperManager/index.ts, packages/@prototype/simulator/src/SimulatorManagerStack/OriginSimulatorLambda/OriginStarterStepFunction/index.ts, packages/@prototype/simulator/src/SimulatorManagerStack/SimulatorManagerLambda/ECSStepFunctionInvoker/index.ts
*Issue #, if available:* #29
* securityGroup config passed properly to ecs.runTask in GraphhopperManager lambda
* removed comments to investigate `securityGroupId` after CDK upgrade
=> fix(simulator/GraphhopperManager): securityGroup config passed properly to ecs.runTask

prototype/simulator/container/src/driver/commands/newOrder.js, prototype/simulator/container/src/driver/data/index.js, prototype/simulator/container/src/driver/state/index.js
*Issue #, if available:* closes #14
- update the simulator to be able to handle multiple orders at the same time
[break]: this PR uses the latest payload structure as per #51 and requires refactoring on the instant delivery provider to change the structure of the messages going to the simulator
=> feat(sim): add support for multiple orders per driver

packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/@lambda/src/commands/startSimulator.js, packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/DestinationStarterStepFunction/@lambda/src/commands/startSimulator.js, packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/DestinationStarterStepFunction/@lambda/src/config/index.js, packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/DestinationStarterStepFunction/@lambda/src/lib/ecs.js, packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/DestinationStarterStepFunction/index.ts, packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/index.ts, packages/@prototype/simulator/src/SimulatorManagerStack/index.ts, prototype/simulator/container/package.json, prototype/simulator/container/src/common/helper/index.js, prototype/simulator/container/src/common/lib/s3.js, prototype/simulator/container/src/destination/config/index.js, prototype/simulator/container/src/destination/destination.js, prototype/simulator/container/src/destination/helper/request.js, prototype/simulator/container/src/destination/index.js, prototype/simulator/container/src/destinationApp.js, prototype/simulator/container/src/driver/index.js
This set of changes adds the ability to replay a remote configured file as source of events (eg. orders) in the simulator. The simulator still retain the option to generate events (orders) in case the configured file is not provided.
=> feat(sim): add ability to replay remote event file

packages/@prototype/appconfig/package.json, packages/@prototype/appconfig/src/AppConfigNestedStack/ConfigStorage/index.ts, packages/@prototype/common/src/constructs/DynamoDB/Table.ts, packages/@prototype/common/src/constructs/DynamoDB/index.ts, packages/@prototype/common/src/constructs/S3/Bucket.ts, packages/@prototype/common/src/constructs/S3/index.ts, packages/@prototype/common/src/constructs/index.ts, packages/@prototype/data-storage/package.json, packages/@prototype/data-storage/src/DataStoragePersistent/index.ts, packages/@prototype/dispatch-setup/package.json, packages/@prototype/external-provider-mock/package.json, packages/@prototype/external-provider-mock/src/ExternalWebhookProviderStack/DataStack/index.ts, packages/@prototype/monitoring/package.json, packages/@prototype/monitoring/src/Monitoring/index.ts, packages/@prototype/provider/package.json, packages/@prototype/simulator/package.json, packages/@prototype/simulator/src/SimulatorDataStack/index.ts, packages/@prototype/simulator/src/SimulatorManagerStack/index.ts
- refactor `HyperlocalBucket` and `HyperlocalTable` to use generic construct names (eg. `Table`, `Bucket`).
- add namespaces to distinguish them from CDK construct 
=> refactor(common): refactor common package to use generic construct names and namespaces

packages/@prototype/dispatch-setup/src/GraphhopperSetup/docker/Dockerfile, packages/@prototype/simulator/src/ECSContainerStack/SimulatorContainer/index.ts, prototype/dispatch/order-dispatcher/src/main/docker/Dockerfile.jvm, prototype/dispatch/order-dispatcher/src/main/docker/instant/sequential/Dockerfile, prototype/scripts/graphhopper/Dockerfile, prototype/simulator/container/Dockerfile
- update all docker files to make sure to use `--platform=linux/arm64` so that the build is compatible with the Graviton2 instances utilised in EC2/Fargate container tasks
=> feat(infra): switch docker build to use linux/arm64 to benefit from Graviton2 

packages/@prototype/data-storage/src/DataStoragePersistent/index.ts, packages/@prototype/provider-impl/src/InstantDeliveryProvider/lambdas/RequestOrderFulfillment/index.ts
=> chore(infra): fix typos on table name and lambda description

packages/@prototype/api-geotracking/src/ApiGeofencing/GeofencingService/index.ts, packages/@prototype/api-geotracking/src/ApiGeotracking/GetDriverLocation/index.ts, packages/@prototype/api-geotracking/src/ApiGeotracking/ListDriversForPolygon/index.ts, packages/@prototype/api-geotracking/src/ApiGeotracking/QueryDrivers/index.ts, packages/@prototype/lambda-functions/src/LambdaFunctions/DriverGeofencingLambda/index.ts, packages/@prototype/lambda-functions/src/LambdaFunctions/DriverLocationCleanupLambda/index.ts, packages/@prototype/lambda-functions/src/LambdaFunctions/DriverLocationUpdateIngestLambda/index.ts, packages/@prototype/lambda-functions/src/LambdaFunctions/DriverStatusUpdateIngestLambda/index.ts, packages/@prototype/live-data-cache/src/LiveDataCache/MemoryDBCluster/index.ts, packages/@prototype/order-manager/src/OrderManager/OrderManagerHandler/index.ts, packages/@prototype/order-manager/src/OrderManager/OrderManagerHelper/index.ts, packages/@prototype/provider-impl/src/ExamplePollingProvider/lambdas/CancelOrder/index.ts, packages/@prototype/provider-impl/src/ExamplePollingProvider/lambdas/ExamplePolling/index.ts, packages/@prototype/provider-impl/src/ExamplePollingProvider/lambdas/GetOrderStatus/index.ts, packages/@prototype/provider-impl/src/ExamplePollingProvider/lambdas/RequestOrderFulfillment/index.ts, packages/@prototype/provider-impl/src/ExampleWebhookProvider/lambdas/CancelOrder/index.ts, packages/@prototype/provider-impl/src/ExampleWebhookProvider/lambdas/ExampleCallback/index.ts, packages/@prototype/provider-impl/src/ExampleWebhookProvider/lambdas/GetOrderStatus/index.ts, packages/@prototype/provider-impl/src/ExampleWebhookProvider/lambdas/RequestOrderFulfillment/index.ts, packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/DestinationStatusUpdateLambda/index.ts, packages/@prototype/simulator/src/SimulatorManagerStack/OriginSimulatorLambda/OriginStatusUpdateLambda/index.ts, packages/@prototype/simulator/src/SimulatorManagerStack/OriginSimulatorLambda/index.ts, packages/@prototype/simulator/src/SimulatorManagerStack/StatisticsLambda/index.ts
*Issue #, if available:* NA, error present on CDK (see https://github.com/aws/aws-cdk/issues/18282 )
- add workaround to enforce the default Redis port to MemoryDB and use that value in the Lambda environment variable. The previous version had issues as per link above 
=> fix(infra): fix usage of memorydb port and add a workaround to avoid runtime errors

packages/@prototype/simulator/src/SimulatorManagerStack/DestinationSimulatorLambda/DestinationGeneratorStepFunction/@lambda/package.json, packages/@prototype/simulator/src/SimulatorManagerStack/OriginSimulatorLambda/OriginGeneratorStepFunction/@lambda/package.json
- fix `nohoist` configuration on lambdas to include `nanoid` instead of the deprecated `shortid`
=> fix(lambda): fix nohoist configuration to add nanoid

packages/@prototype/dispatch-setup/src/GraphhopperSetup/docker/Dockerfile
* fix graphhopper version with `4.0` tag when checking out to build for docker
* build graphhopper with `-DskipTests=true` switch as build fails on x86
=> feat(graphhopper): docker build with skipTest as it's failing on x86

prototype/infra/lib/stack/root/SimulatorMainStack/index.ts
- swap origin/destination ecs task variables as they were linked to the wrong property
=> fix(simulator): swap origin/destination properties

packages/@prototype/simulator/src/ECSContainerStack/index.ts
- fix simulator env name typo `ORIGN_EXECUTIONID_INDEX` => `ORIGIN_EXECUTIONID_INDEX`
=> fix(simulator): typo on env variable name 

prototype/dispatch/order-dispatcher/deploy/application.properties, prototype/dispatch/order-dispatcher/src/main/docker/instant/sequential/Dockerfile, prototype/dispatch/order-dispatcher/src/main/docker/instant/sequential/config/application-docker.properties, prototype/dispatch/order-dispatcher/src/main/resources/application.properties
* Dispatch ECS service was recycling containers over and over because logger threw an exception that it was not able to create the log file. Permission added in the Dockerfile and simplified logfile path.
=> fix(dispatcher): quarkus app is able to create log file

packages/@prototype/instant-delivery-provider/src/DispatchEngineOrchestrator/DispatchEngineOrchestrator/index.ts, packages/@prototype/instant-delivery-provider/src/DispatchEngineOrchestrator/GeoClusteringManager/index.ts, packages/@prototype/instant-delivery-provider/src/DispatchEngineOrchestrator/index.ts, packages/@prototype/instant-delivery-provider/src/DriverEventHandler/SubMinuteExecutionStepFunction/index.ts, packages/@prototype/instant-delivery-provider/src/DriverEventHandler/index.ts, packages/@prototype/order-manager/src/OrderManager/OrderManagerStepFunction/index.ts, prototype/infra/config/default.yaml
- setup Redis cluster mode with one shard
- define order manager step functions timeout
- define instant delivery step functions timeout
- rename property spelled wrongly inside the instant delivery provider
=> chore(instant-delivery): add in timeouts to long running step functions

packages/@prototype/dispatch-setup/src/DispatchSetup/DispatchEcsService/index.ts, packages/@prototype/dispatch-setup/src/DispatchSetup/index.ts, packages/@prototype/dispatch-setup/src/GraphhopperSetup/index.ts, prototype/infra/config/default.yaml, prototype/infra/lib/stack/nested/DispatcherStack/index.ts, prototype/infra/lib/stack/nested/ProviderStack/index.ts, prototype/infra/lib/stack/root/BackendStack/index.ts
- add ability to configure ECS Task count for both Graph Hopper and Dispatch Engine
=> chore(infra): add ecs task count as configuration parameter

packages/@prototype/data-storage/src/DataStoragePersistent/index.ts, packages/@prototype/dispatch-setup/src/DispatchSetup/DispatchEcsService/index.ts, packages/@prototype/dispatch-setup/src/DispatchSetup/DispatchHosting/index.ts, packages/@prototype/dispatch-setup/src/DispatchSetup/index.ts, prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/docker/Dockerfile, prototype/infra/lib/stack/nested/DispatcherStack/index.ts, prototype/infra/lib/stack/nested/MicroServiceStack/index.ts, prototype/infra/lib/stack/root/BackendStack/index.ts
Fixing deployment bug for SSM parameters for dispatcher.
=> fix(dispatch/infra): ssm parameters passed around as objects instead of string keys

prototype/simulator/website/src/components/EntitySimulationSummary/index.tsx, prototype/simulator/website/src/pages/Destinations/index.tsx, prototype/simulator/website/src/pages/Origins/index.tsx
- fix the common `EntitySimulationSummary` component to accept an `entityName` property to use as label
=> fix(web): fix wrong labels on EntitySimulationSummary

packages/@prototype/api-geotracking/src/ApiGeotracking/QueryDrivers/@lambda/index.js
- fix while loop condition in `QueryDrivers` lambda to avoid infinite loop when drivers are missing from the system (either no IDLE drivers are available or no drivers are logged in)
=> fix(geotracking): fix while loop condition in QueryDrivers lambda 

packages/@prototype/data-storage/src/DataStoragePersistent/index.ts, packages/@prototype/dispatch-setup/src/DispatchSetup/SameDayDispatchEcsService/index.ts, packages/@prototype/dispatch-setup/src/DispatchSetup/index.ts, prototype/infra/lib/stack/nested/DispatcherStack/index.ts, prototype/infra/lib/stack/root/BackendStack/index.ts, reports/cfn-nag-report.json
*Issue #, if available:* #110, #111
* Created a DDB table secondary index for `solverJobId` and wired it up with read access by sdd docker's taskrole
=> feat(sdd-jobs): create sdd jobs ddb table solverJobIndex and wire it up

packages/@prototype/dispatch-setup/src/DispatchSetup/SameDayDispatchEcsService/index.ts
to fix errors as:
```
1 validation error detected: Value 'devproto-Dispatcher-SameDayDeliveryDirectPudo-TaskRole-ap-southeast-1' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError)
```
*Description of changes:* 
- update resources name to avoid deployment errors due to length limitations on some services 
=> fix(ssd-infra): fix resources name to avoid error during deployment

packages/@prototype/instant-delivery-provider/src/DispatchEngineOrchestrator/OrchestratorHelperLambda/@lambda/src/lib/routing.js
- update the graph hopper routing object returned for instant delivery to include distance/time as object with their respective value/unit represented explicitly
=> fix(instant-delivery): update routing details information to include unit/value

packages/@aws-play/cdk-apigateway/src/RestApi/index.ts
- remove un-required _dummy_ method from the `RestApi` common construct
=> fix(infra): remove dummy method (ANY) from the RestApi construct

packages/@prototype/dispatch-setup/src/GraphhopperSetup/docker/Dockerfile, prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/docker/Dockerfile, prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/docker/Dockerfile, prototype/dispatch/delivery-dispatch/pom.xml, reports/docker/delivery-dispatch-instant-sequential-report.txt, reports/docker/delivery-dispatch-sameday-directpudo-report.txt, reports/docker/graphhopper-50-report.txt
* bump Graphhopper version from `4.0` to `5.0`
=> chore(graphhopper): use Graphhopper5 in delivery-dispatch and docker images

prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/Order.java, prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/api/DispatchService.java, prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/data/DdbHubService.java, prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/domain/planning/PlanningHub.java, prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/planner/solution/SolutionConsumer.java
* filter orders from the request that have pikcup/dropoff locations that are outside the cached area
* fix `planningIDs must be unique` error
=> fix(delivery-dispatch/app/sameday): planningIDs unique; filter non-cached locations

packages/@prototype/data-storage/src/DataStoragePersistent/DatabaseSeeder/sameday-directpudo-vehicle-capacity-seeder.ts, packages/@prototype/data-storage/src/DataStoragePersistent/index.ts, packages/@prototype/dispatch-setup/src/DispatchSetup/SameDayDispatchEcsService/index.ts, packages/@prototype/dispatch-setup/src/DispatchSetup/index.ts, prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/api/DispatchService.java, prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/config/DdbProperties.java, prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/data/DdbVehicleCapacityService.java, prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/data/VehicleCapacity.java, prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/resources/application.properties, prototype/infra/config/default.yaml, prototype/infra/lib/stack/nested/DispatcherStack/index.ts, prototype/infra/lib/stack/root/BackendStack/index.ts, reports/cfn-nag-report.json
* add DDB table with default data preloaded for vehicle capacities
* enable SDD dispatcher to load vehicle capacity information from DDB for the vehicles
=> feat(delivery-dispatch): parameterizable vehicle capacities

packages/@prototype/data-storage/src/DataStoragePersistent/InstantDeliveryDataStorage/index.ts
When creating the idx-instant-delivery-provider-orders-jobid index, the partitionKey uses 'jobid' name (all lower case) when the name should actually be 'jobId', with an upper case "i"
=> Fix index idx-instant-delivery-provider-orders-jobid

packages/@prototype/data-storage/src/DataStoragePersistent/RootDataStorage/seeder/demographic-area-provider-engine.ts, prototype/simulator/container/src/destination/destination.js
- update simulator to send `deliveryType` also for the default provider (eg. instant delivery)
- update default configuration to route orders based on the delivery type with higher priority 
=> feat(order-orchestration): delivery type routing

packages/@prototype/simulator/src/ECSContainerStack/index.ts
- remove `SecretStringValueBeta1.fromUnsafePlaintext` from the codebase and replace it with `SecretValue.unsafePlainText`
=> fix(infra): remove deprecated SecretStringValueBeta1

packages/@prototype/data-storage/src/DataStoragePersistent/RootDataStorage/seeder/demographic-area-provider-engine.ts, packages/@prototype/order-manager/src/OrderManager/ProviderRuleEngine/@lambda/src/commands/cancelOrderFromProvider.js, packages/@prototype/order-manager/src/OrderManager/ProviderRuleEngine/@lambda/src/commands/sendToProvider.js
- fix demographic area settings to remove ambiguity on the type of results returned by the provider rule engine. In the previous iteration was possible to have both `instant` and `same-day` delivery as output (with the second one being used if the first doesn't return a result), which lead to some inconsistency on the way the package is handled by the provider. While this _could_ be possible in some instances, for this sample we'll try to handle the incoming order with either `instant` or `same-day` provider (and, possibly, handle it with external providers to simulate some underlying issues on original provider)
- added some extra information in the logs to help further debugging
By submitting this pull request, I confirm that you can …
=> fix(rule-engine): fix demographic area settings

docs/quick-start.md, packages/@prototype/external-provider-mock/src/ExternalPollingProviderStack/index.ts, packages/@prototype/external-provider-mock/src/ExternalWebhookProviderStack/WebhookInvoker/index.ts, packages/@prototype/external-provider-mock/src/ExternalWebhookProviderStack/index.ts, packages/@prototype/order-manager/src/OrderManager/ProviderRuleEngine/index.ts, packages/@prototype/order-manager/src/OrderManager/index.ts, prototype/infra/bin/dev-infra.ts, prototype/infra/config/default.yaml, prototype/infra/lib/stack/nested/CustomResourcesStack/index.ts, prototype/infra/lib/stack/nested/OrderOrchestrationStack/index.ts, prototype/infra/lib/stack/nested/ProviderStack/index.ts, prototype/infra/lib/stack/root/BackendStack/index.ts, prototype/infra/lib/stack/root/ExternalProviderStack/index.ts, prototype/infra/package.json, reports/cfn-nag-report.json
*Issue #, if available:* closes #18
* external mock provider manual deployment and config update not needed anymore, all automated; deployed API urls stored as SSM param
* external mock provider supports variable number of providers to deploy (only depends on config)
* `externalProviderConfig` configuration structure changed
* `quickstart` doc updated
`ProviderStack` , `OrderManager` and `CustomResourcesStack` still need to be generalized to support variable number of external providers set in config (`prio:low` for now)
=> feat: automated deployment

LICENSE_THIRDPARTY.txt, README.md, prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/resources/application.properties, prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/resources/application.properties, prototype/dispatch/delivery-dispatch/core/routing/src/main/java/dev/aws/proto/core/routing/route/GraphhopperRouter.java, prototype/scripts/.env-example, prototype/scripts/detach-iot-policies.sh, prototype/scripts/dev-reset-sdd-docker.sh, prototype/scripts/pull-appvariables-js.sh, prototype/scripts/stop-ecs-tasks.sh, prototype/scripts/stop-simulators-iot.sh, prototype/scripts/stop-stepfunctions.sh, prototype/scripts/truncate-ddb-tables.sh, prototype/simulator/website/.eslintrc.js, prototype/simulator/website/LICENSE_THIRDPARTY.txt, prototype/simulator/website/package.json, reports/yarn-audit.html, yarn.lock
* by default use 5-decimal rounding on lat/longs (1.1m)
* add routing retry mechanism if there's a routing error and try on lower accuracy
* dev scripts require a `.env` file with profile/region/namespace vars set
=> fix(delivery-dispatch/routing): introduce lat/lng accuracy

packages/@prototype/monitoring/src/Monitoring/index.ts, prototype/infra/bin/dev-infra.ts
Enforce v2 IMDS when EC2 instances are spun up. More info in [EC2 documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html)
=> feat(infra): add require IMDSv2 for asg created instances

prototype/dispatch/delivery-dispatch/apps/app-core/src/main/java/dev/aws/proto/apps/appcore/api/DispatchService.java, prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/java/dev/aws/proto/apps/instant/sequential/api/DispatchResource.java, prototype/dispatch/delivery-dispatch/apps/instant-sequential/src/main/java/dev/aws/proto/apps/instant/sequential/api/DispatchService.java, prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/api/DispatchResource.java, prototype/dispatch/delivery-dispatch/apps/sameday-directpudo/src/main/java/dev/aws/proto/apps/sameday/directpudo/api/DispatchService.java
Create `createdAt` at `DispatchResoruce`'s `assign-drivers` handler and pass it to dispatcher to avoid creating duplicated assignment entries.
=> fix(dispatcher): pass createdAt to dispatcher

packages/@prototype/instant-delivery-provider/src/DispatchEngineOrchestrator/OrchestratorHelperLambda/@lambda/src/lib/routing.js
NA
Fix routing profile for graph hopper to avoid error on dispatching orders to the driver
=> fix(orchestrator): add routing profile to graph hopper invocation
